name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "monitor_dfg024soqtfoehw8"
database_id = "dd9f4f9f-3425-41c2-a798-6d98f8791f8f"

[version_metadata]
binding = "CF_VERSION_METADATA"
